services:
  db:
    container_name: "moustracks_db"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5633:5432
